//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public string ProductType { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string IsBooked { get; set; }
        public string ProductFare { get; set; }
    }
}
